### ISSUE TITLE
Links on words

### ISSUE THREAD

**Issue by ghost** [russelporosky/jQuery.awesomeCloud.plugin#2]
Make it work with <a> tags as well! Make it a tag cloud, not just a word cloud!

**Comment by leopoldodonnell** [comment]
This would be super - you've got a really nice cloud.
It's also probably not that difficult (HAHA) - One approach might go like this...
- Look for an href attribute in the element and store that along with the word and weight
- Have AwesomeCloud.putWord return a rectangle for each word drawn and store that in the words array
- Add a click event handler that traverses the word array looking for a 'hit'
- Trigger a plugin specific event that clients call look for that gets the word, weight and href (if it exists)

I know - easier said than done and then folks will want hightlighting on mouseover and all sorts of other requests.
It'd be nice to see this done, but we've all got limited time...

**Comment by timdream** [comment]
Hi @indyarmy, someone point me to your work here :)

I have since isolate the library part into https://github.com/timdream/wordcloud2.js (without jQuery dependency and parsing text from existing content on page); this issue is exactly what I have in my mind, document in timdream/wordcloud2.js#7.

If you are able to contribute the code there it will be greatly appreciated.

**Comment by ghost** [comment]
Tags have been added! Finally! Thanks to @slaFFik and his work on issue #6. And thanks to you @leopoldodonnell - that is pretty much exactly how the event listener works now.
