### ISSUE TITLE
awesomeCloud is a word cloud plugin for jQuery. It uses the HTML <canvas> element.

### ISSUE THREAD

**Issue by nilesh1021** [russelporosky/jQuery.awesomeCloud.plugin#3]
Hi,
 I am student. I want to know that how to run awesomeCloud on the internet explorer 8.

[awesomeCloud is a word cloud plugin for jQuery. It uses the HTML <canvas> element.]

Your example of http://indyarmy.com/awesomeCloud/   on this site running in IE8.

But after downloading it is not running on IE8.

So how your example is running????????????????????

Please help..........

Thanks

**Comment by ghost** [comment]
Without more info, I'm not sure what I can help with. My best advice would be to use Chrome (or Firefox with the Web Developer extension) to make sure there are no other Javascript errors, make sure the contents of your containing DIV are in the right format (as shown in the readme file), and as a last resort, make sure the container div has a specified width and height (I haven't done extensive testing in IE, so I don't know if the HasLayout bug will affect the plugin).

Let me know how it turns out, and I'll help if I can :)

**Comment by ghost** [comment]
Closed and presumed to be figured out.
